config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'top#index'
  get 'members/senko'
  get 'members/chiyokagura'
  get 'members/f'
  resources :users
  resources :members
  get 'home/index'
  get 'performances/index'
  get 'infomations/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
    belongs_to :user, optional: true
    mount_uploader :image, ImageUploader
end

app/models/performance.rb
class Performance < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/infomations_controller.rb
class InfomationsController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # before_action :set_member, only: [:destroy, :show]
  before_action :authenticate_user!, only: [:show, :edit, :destroy, :edit, :update, :new]

  def index
  end

  def create
    # binding.pry
    # @member = Member.new(name: member_params[:name], nickname: member_params[:nickname], job: member_params[:job], text: member_params[:text], image: member_params[:image], year: member_params[:year])
    @member = Member.new(member_params)
    @member.save!
    redirect_to members_path, notice: 'データベースに保存されました'
  end
  
  # def show
  # end
# showで@member_その学年が入恋した年の演舞 = Member.where(year: その年)
# 表示順を考慮するカラムが必要かも?
# 本番環境同様のbasic認証で二段階認証?
  def senko
    @member_senko = Member.where(year: 2017)
  end

  def chiyokagura
    @member_chiyokagura = Member.where(year: 2018)
  end

  def f
    @member_f = Member.where(year: 2019)
  end


  def new
    @member = Member.new
  end

  def destroy
    @member = Member.find_by(id: params[:id])
    @member.destroy
    redirect_to members_path, notice: '削除しました'
  end
  # member.idを作る必要あり？
  # groupで分けたほうがいいかも、００代とか

  def edit
    @member = Member.find_by(id: params[:id])
  end

  def update
    @member = Member.find_by(id: params[:id])
    @member.update(name: member_params[:name], job: member_params[:job], text: member_params[:text], image: member_params[:image], year: member_params[:year], memberid: member_params[:memberid])
    redirect_to members_path, notice: '編集されました'
  end

private

  def member_params
    params.permit(:name, :job, :text, :image, :year, :memberid)
  end

  def set_member
    @member = Member.find(params[:id])
  end

end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  def index
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

  def activity
  end

  def infomation
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infomations_helper.rb
module InfomationsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/members/_chiyokagura_member.html.haml
= render 'shared/header'
.kaisei 
  %p 2回生
.kaisei-img
  = image_tag ('2nd_top.png')
.kaisei-main
  %p.kaisei-main__logo - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・   ▼ profile ▼   - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('sawayakasatoru.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 代表   /旗担当 /合宿担当
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('painijosaidaikouyakusu.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 副代表 /衣装制作
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('taguchiemiko.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 副代表 /合宿担当 /会計担当
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('doppio.png')
    .kaisei-main__people--job
      %p 練習担当長 /振り制 /HP制作
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  -# - @member_chiyokagura.each do |member|
  -#   %p= member.name
  -#   %p= member.nickname
  -#   %p= member.text

app/views/members/_f_member.html.haml
= render 'shared/header'
.kaisei 
  %p 1回生
.kaisei-img
  = image_tag ('1st_top.png')
.kaisei-main
  %p.kaisei-main__logo - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・   ▼ profile ▼   - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('sawayakasatoru.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 代表   /旗担当 /合宿担当
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('painijosaidaikouyakusu.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 副代表 /衣装制作
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('taguchiemiko.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 副代表 /合宿担当 /会計担当
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('doppio.png')
    .kaisei-main__people--job
      %p 練習担当長 /振り制 /HP制作
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ  
  -# - @member_chiyokagura.each do |member|
  -#   %p= member.name
  -#   %p= member.nickname
  -#   %p= member.text

app/views/members/_header-box.html.haml
.header-box
  .header-box__list
    %p.header-box__list--font トップページ
  .header-box__list
    %p.header-box__list--font 1回生
  .header-box__list
    %p.header-box__list--font 2回生
  .header-box__list
    %p.header-box__list--font 3回生
  .header-box__list
    %p.header-box__list--font 4回生
  .header-box__list
    %p.header-box__list--font OBOGさん

app/views/members/_senko_member.html.haml
= render 'shared/header'
.kaisei 
  %p 3回生
.kaisei-img
  = image_tag ('3rd_top.png'), class: 'kaisei-img__img'
.kaisei-main
  %p.kaisei-main__logo - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・   ▼ profile ▼   - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('sawayakasatoru.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 代表   /旗担当 /合宿担当
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('painijosaidaikouyakusu.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 副代表 /衣装制作
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('taguchiemiko.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 副代表 /合宿担当 /会計担当
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('doppio.png')
    .kaisei-main__people--job
      %p 練習担当長 /振り制 /HP制作
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  -# - @member_senko.each do |member|
  -#   %p= member.name
  -#   %p= member.nickname
  -#   %p= member.text

app/views/members/chiyokagura.html.haml
= render 'shared/header'
.member
  .kaisei 
    %p 2回生
    = image_tag ('2nd_top.png'), class: 'kaisei-img'
  .kaisei-main
    %p.text  ▼ profile ▼
    %p.text-t 〜 個人プロフィール 〜
    - @member_chiyokagura.each do |member|
      .member-box
        .member-box__image
          = image_tag member.image.url
        .member-box__name
          %p= member.name
        .member-box__text
          %p= member.text
        .member-box__job
          %p= member.job
        - if user_signed_in?
          = link_to edit_member_path(member.id) do
            %p.edit-btn 編集する
- if user_signed_in?
  %a{href: '/members/new', class: 'go-to-new'}メンバー投稿ページへ
  = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'go-to-logout'

app/views/members/edit.html.haml
.member-edit__top
  %p member編集画面
.member-before-image
  = image_tag @member.image.url
  %p 編集前の画像（ファイル変更してもこの画面上では変わりません）

.member-edit
  = form_for @member do |f|
    .member-edit__box
      %p 変更する画像を選択
      = f.file_field :image, name: "image", class: "member-edit__box--image"
      = f.text_field :name, placeholder: "#{@member.name}", name: "name", class: "member-edit__box--name"
      = f.text_field :job, placeholder: "#{@member.job}", name: "job", class: "member-edit__box--job"
      = f.text_field :text, placeholder: "#{@member.text}", name: "text", name: "text", class: "member-edit__box--text"
      = f.text_field :year, placeholder: "#{@member.year}", name: "year", name: "year", type: "string", class: "member-edit__box--year"
      = f.text_field :memberid, placeholder: "#{@member.memberid}", name: "memberid", type: "string", class: "member-edit__box--memberid"
      = f.submit '編集', class: "member-edit-btn"
      %p.attention-head 注意事項!!!
      %p.attention ・編集時に画像ファイルを選択しないとエラーが出ます(後日修正予定)
      %p.attention ・最後の数字は並び変える時に使ってください
      %p.attention ・enterキーを連打しすぎると勝手に投稿されます。


= link_to member_path(@member.id), class: "delete-btn", method: :delete do
  %p 削除する

app/views/members/f.html.haml
= render 'shared/header'
.member
  .kaisei 
    %p 1回生
    = image_tag ('1st_top.png'), class: 'kaisei-img'
  .kaisei-main
    %p.text  ▼ profile ▼
    %p.text-t 〜 個人プロフィール 〜
    - @member_f.each do |member|
      .member-box
        .member-box__image
          = image_tag member.image.url
        .member-box__name
          %p= member.name
        .member-box__text
          %p= member.text
        .member-box__job
          %p= member.job
        - if user_signed_in?
          = link_to edit_member_path(member.id) do
            %p.edit-btn 編集する
- if user_signed_in?
  %a{href: '/members/new', class: 'go-to-new'}メンバー投稿ページへ
  = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'go-to-logout'

app/views/members/f_member.html.haml
= render 'shared/header'
.kaisei 
  %p 1回生
.kaisei-img
  = image_tag ('1st_top.png')
.kaisei-main
  %p.kaisei-main__logo - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・   ▼ profile ▼   - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('sawayakasatoru.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 代表   /旗担当 /合宿担当
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('painijosaidaikouyakusu.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 副代表 /衣装制作
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('taguchiemiko.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 副代表 /合宿担当 /会計担当
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('doppio.png')
    .kaisei-main__people--job
      %p 練習担当長 /振り制 /HP制作
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ

app/views/members/index.erb
<%= render 'shared/header' %>

app/views/members/index.html.haml
= render 'shared/header'
.activity
  .activity__header
    %p.activity__header--logo ▽ M E M B E R ▽
    %p.activity__header--sub 〜 メンバー紹介 〜
  %p.people-now ▼ 現 役 生 ▼
  .people-box
    .people-box__image
      = link_to  members_f_path do
        = image_tag ('1st_yosakoier.png')
    %p.people-box__text 
    %br 2019『廻覆～ヱフ～』でデビューしました。
    %br 令和にふさわしい元気もりもりごはんぱわーな代です
  .people-box
    .people-box__image
      = link_to  members_chiyokagura_path do
        = image_tag ('2nd_yosakoier.png')
    %p.people-box__text 
    %br 2018『千妖神樂』でデビューしました。
    %br 明るくて仲良しな代です。
  .people-box
    .people-box__image
      = link_to members_senko_path do
        = image_tag ('3rd_yosakoier.png')
    %p.people-box__text 
    %br 2017年『閃煌』でデビューしました。
    %br 2019『廻覆～ヱフ～』を中心になって制作しお披露目しました！
    %br 全力で一生懸命な代です！
- if user_signed_in?
  %a{href: '/members/new', class: 'go-to-new'}メンバー投稿ページへ
  = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'go-to-logout'

app/views/members/new.html.haml
- if user_signed_in?
  .members-create-top
    %p メンバー追加画面 / 年度は半角でお願いします
  .member-create
    = form_for @member do |f|
      = f.text_field :name, placeholder: "よさ名", name: "name"
      = f.text_field :job, placeholder: "役職", name: "job"
      = f.text_field :text, placeholder: "テキスト", name: "text", name: "text"
      = f.text_field :year, placeholder: "何年入恋か？", name: "year", name: "year", type: "string"
      = f.text_field :memberid, placeholder: "メンバーid", name: "memberid", type: "string"
      = f.file_field :image, name: "image"
      = f.submit '投稿'
      
- else
  = link_to new_user_session_path do
    %p you must log_in !!
  %p (if you've already signed_in, no problem)

app/views/members/senko.html.haml
= render 'shared/header'
.member
  .kaisei 
    %p 3回生
    = image_tag ('3rd_top.png'), class: 'kaisei-img'
  .baka-logo
    %h1 17代目 鳳遙恋
    %h2 『馬鹿になれ』
    %p 『馬鹿になれ』みんなはこの言葉を見てどう感じるでしょうか？
    %p 「馬鹿」という言葉は本来頭が良くないとか常識を知らないという意味で
    %p 使われる言葉で、あんまりいい印象を受けない人もいると思います。
    %p でも自分はこの言葉が大好きです。
    %p 自分が過ごしてきた環境では「野球馬鹿」という言葉があって、一つのことに
    %p 熱心に打ち込む「○◯馬鹿」は愛されるべき褒め言葉だと思います。
    %p みんなもわかってると思うけど、鳳遙恋にはいろんな人が所属しています。
    %p もちろんよさこいが好きな人、遊びが好きな人、飲みが好きな人、交流が好きな人、
    %p よさこい馬鹿、遊び馬鹿、飲み馬鹿、交流馬鹿 ...etc
    %p 自分はどの道でもいいからみんなに自分が馬鹿になれる道を見つけて欲しいです。
    %p そして周りのみんなはそれぞれの馬鹿を応援してあげて欲しいです。
    %p あとひとつ、俺らの先輩は間違いなく愛されるべきおバカな人達でした。
    %p あの人たちと比べて馬鹿になりきれない俺らは色々と言われてきたけど、
    %p 殻を破って馬鹿になった奴らのやることほど恐ろしいものは無いと思います。
    %p 2019年11月、殻を破って馬鹿になったみんなと東急メイン踊りたいです。
    %p 馬鹿で感動を生み出そう。その為に1年間馬鹿になれ。
    %h3 17代目 代表 爽やかサトル
  .kaisei-main
    %p.text  ▼ profile ▼
    %p.text-t 〜 個人プロフィール 〜
    - @member_senko.each do |member|
      .member-box
        .member-box__image
          = image_tag member.image.url
        .member-box__name
          %p= member.name
        .member-box__text
          %p= member.text
        .member-box__job
          %p= member.job
        - if user_signed_in?
          = link_to edit_member_path(member.id) do
            %p.edit-btn 編集する
- if user_signed_in?
  %a{href: '/members/new', class: 'go-to-new'}メンバー投稿ページへ
  = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'go-to-logout'

app/views/members/senko_member.html.haml
= render 'shared/header'
.kaisei 
  %p 3回生
.kaisei-img
  = image_tag ('3rd_top.png')
.kaisei-main
  %p.kaisei-main__logo - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・   ▼ profile ▼   - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・ - ・
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('sawayakasatoru.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 代表   /旗担当 /合宿担当
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('painijosaidaikouyakusu.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 副代表 /衣装制作
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('taguchiemiko.png')
    .kaisei-main__people--job
      %p 鳳遙恋17代目 副代表 /合宿担当 /会計担当
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ
  .kaisei-main__people
    .kaisei-main__people--image
      = image_tag ('doppio.png')
    .kaisei-main__people--job
      %p 練習担当長 /振り制 /HP制作
    .kaisei-main__people--text
      %p 楠にジャーマンスープレックスする男って書いてって頼まれたよ 書いたよ

app/views/performances/_kakoenbu.erb
<p class="body-sub__logo">▽ 過 去 演 舞 紹 介 ▽</p>
<div class="image-box">
  <div class="image-box__enbu">
    <div class="image-box__enbu--img">
      <a href="https://www.youtube.com/watch?v=hqx-GVwI3xU"><%= image_tag ('chiyokagura_onna.jpg') %></a>
    </div>
    <p class="image-box__enbu--exp">
      2018年度演舞 千妖神樂
    </p>
  </div>
  <div class="image-box__enbu">
    <div class="image-box__enbu--img">
      <a href="https://www.youtube.com/watch?v=_Fj-9VE6iMc"><%= image_tag ('senko.jpg') %></a>
    </div>
    <p class="image-box__enbu--exp">
      2017年度演舞 閃煌
    </p>
  </div>
  <div class="image-box__enbu">
    <div class="image-box__enbu--img">
      <a href="https://www.youtube.com/watch?v=UnFrcyHPSfQ&list=PLInNr2cCw0T1z-ETkEHpT0Mhx6FBpDhE7&index=18"><%= image_tag ('canvas.jpg') %></a>
    </div>
    <p class="image-box__enbu--exp">
      2016年度演舞 CANVAS
    </p>
  </div>
  <div class="image-box__enbu">
    <div class="image-box__enbu--img">
      <a href="https://www.youtube.com/watch?v=CrJxRng5Z80&t=75s"><%= image_tag ('roman.jpg') %></a>
    </div>
    <p class="image-box__enbu--exp">
      2015年度演舞 浪漫<br>
      <a href="https://www.youtube.com/watch?v=CrJxRng5Z80&t=75s">youtube</a>
    </p>
  </div>
</div>

app/views/performances/index.erb
<%= render 'shared/header' %>
<div class="performance">
  <div class="performance-header">
    <p class="performance-header__logo">▽ performance introduction ▽</p>
  </div>
  <div class="body-main">
    <div class="body-main__photo">
      <%= image_tag ('soran.jpg') %>
    </div>
    <div class="body-main__f">
      <div class="body-main__f--image">
        ここに廻覆の画像を貼る
      </div>
      <div class="body-main__f--comment">
        ここに廻覆の説明文
      </div>
    </div>
  </div>
<div class="body-sub">
  <%= render 'performances/kakoenbu' %>
  <p class="credit">
    ~ hoyoren ~
  </p>
</div>